# Generated by Django 3.2.3 on 2021-06-10 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dialogs', '0006_auto_20200604_1829'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={'verbose_name': 'message', 'verbose_name_plural': 'message'},
        ),
        migrations.AlterField(
            model_name='message',
            name='is_readed',
            field=models.BooleanField(default=False, verbose_name='readed'),
        ),
        migrations.AlterField(
            model_name='message',
            name='message_image',
            field=models.ImageField(blank=True, upload_to='images/messages/', verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='message',
            name='message_text',
            field=models.TextField(verbose_name='text message'),
        ),
        migrations.AlterField(
            model_name='message',
            name='message_time',
            field=models.DateTimeField(verbose_name='time of sending'),
        ),
        migrations.AlterField(
            model_name='message',
            name='reciever_visibility',
            field=models.BooleanField(default=True, verbose_name='reviever visible'),
        ),
        migrations.AlterField(
            model_name='message',
            name='sender_visibility',
            field=models.BooleanField(default=True, verbose_name='sender visible'),
        ),
    ]
