# Generated by Django 3.2.3 on 2021-06-10 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0008_post_post_image_url'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'verbose_name': 'comment', 'verbose_name_plural': 'comments'},
        ),
        migrations.AlterModelOptions(
            name='like',
            options={'verbose_name': 'like', 'verbose_name_plural': 'likes'},
        ),
        migrations.AlterModelOptions(
            name='post',
            options={'verbose_name': 'post', 'verbose_name_plural': 'posts'},
        ),
        migrations.AlterField(
            model_name='comment',
            name='comment_pubdate',
            field=models.DateTimeField(verbose_name='pubdata'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='comment_text',
            field=models.CharField(max_length=350, verbose_name='comment_text'),
        ),
        migrations.AlterField(
            model_name='post',
            name='post_image',
            field=models.ImageField(blank=True, upload_to='images/post/', verbose_name='post image'),
        ),
        migrations.AlterField(
            model_name='post',
            name='post_image_url',
            field=models.ImageField(blank=True, upload_to='', verbose_name='URL post image'),
        ),
        migrations.AlterField(
            model_name='post',
            name='post_text',
            field=models.TextField(verbose_name='post text'),
        ),
        migrations.AlterField(
            model_name='post',
            name='post_time',
            field=models.DateTimeField(verbose_name='creation ime'),
        ),
        migrations.AlterField(
            model_name='post',
            name='post_title',
            field=models.CharField(blank=True, max_length=150, verbose_name='title'),
        ),
    ]
